/**
 * Build starter phrases (~5 per pack × 50 packs).
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outPath = join(__dirname, '../src/data/phrases.json')

const BASE = [
  { it: 'Buongiorno!', es: '¡Buenos días!' },
  { it: 'Buonasera!', es: '¡Buenas tardes / noches!' },
  { it: 'Come stai?', es: '¿Cómo estás?' },
  { it: 'Sto bene, grazie.', es: 'Estoy bien, gracias.' },
  { it: 'Piacere di conoscerti.', es: 'Encantado/a de conocerte.' },
  { it: 'Come ti chiami?', es: '¿Cómo te llamas?' },
  { it: 'Mi chiamo…', es: 'Me llamo…' },
  { it: 'Di dove sei?', es: '¿De dónde eres?' },
  { it: 'Sono di…', es: 'Soy de…' },
  { it: 'Parli italiano?', es: '¿Hablas italiano?' },
  { it: 'Un po’.', es: 'Un poco.' },
  { it: 'Non capisco.', es: 'No entiendo.' },
  { it: 'Puoi ripetere, per favore?', es: '¿Puedes repetir, por favor?' },
  { it: 'Parla più lentamente.', es: 'Habla más despacio.' },
  { it: 'Come si dice…?', es: '¿Cómo se dice…?' },
  { it: 'Cosa significa…?', es: '¿Qué significa…?' },
  { it: 'Quanto costa?', es: '¿Cuánto cuesta?' },
  { it: 'Dov’è il bagno?', es: '¿Dónde está el baño?' },
  { it: 'Scusi / Scusa.', es: 'Disculpe / Perdón.' },
  { it: 'Non c’è problema.', es: 'No hay problema.' },
  { it: 'Mi dispiace.', es: 'Lo siento.' },
  { it: 'Aiuto!', es: '¡Ayuda!' },
  { it: 'Che ora è?', es: '¿Qué hora es?' },
  { it: 'A che ora…?', es: '¿A qué hora…?' },
  { it: 'Dove si trova…?', es: '¿Dónde está / se encuentra…?' },
  { it: 'Alla sinistra / A destra.', es: 'A la izquierda / A la derecha.' },
  { it: 'Vado a casa.', es: 'Voy a casa.' },
  { it: 'Andiamo!', es: '¡Vamos!' },
  { it: 'Aspetta un momento.', es: 'Espera un momento.' },
  { it: 'Ci vediamo dopo.', es: 'Nos vemos después.' },
  { it: 'A presto!', es: '¡Hasta pronto!' },
  { it: 'Buona fortuna!', es: '¡Buena suerte!' },
  { it: 'Buon appetito!', es: '¡Buen provecho!' },
  { it: 'Salute!', es: '¡Salud!' },
  { it: 'Posso avere…?', es: '¿Puedo tener / pedir…?' },
  { it: 'Vorrei un caffè.', es: 'Quisiera un café.' },
  { it: 'Il conto, per favore.', es: 'La cuenta, por favor.' },
  { it: 'È delizioso!', es: '¡Está delicioso!' },
  { it: 'Ho fame.', es: 'Tengo hambre.' },
  { it: 'Ho sete.', es: 'Tengo sed.' },
  { it: 'Ho freddo / caldo.', es: 'Tengo frío / calor.' },
  { it: 'Mi piace…', es: 'Me gusta…' },
  { it: 'Non mi piace…', es: 'No me gusta…' },
  { it: 'Preferisco…', es: 'Prefiero…' },
  { it: 'Devo andare.', es: 'Tengo que irme.' },
  { it: 'Possiamo incontrarci?', es: '¿Podemos encontrarnos?' },
  { it: 'Ti chiamo più tardi.', es: 'Te llamo más tarde.' },
  { it: 'Mandami un messaggio.', es: 'Mándame un mensaje.' },
  { it: 'Che bello!', es: '¡Qué bonito / qué bien!' },
  { it: 'Non lo so.', es: 'No lo sé.' },
  { it: 'Penso di sì.', es: 'Creo que sí.' },
  { it: 'Penso di no.', es: 'Creo que no.' },
  { it: 'Sembra interessante.', es: 'Parece interesante.' },
  { it: 'Hai ragione.', es: 'Tienes razón.' },
  { it: 'Hai torto.', es: 'Estás equivocado/a.' },
  { it: 'Cosa fai?', es: '¿Qué haces?' },
  { it: 'Lavoro / Studio.', es: 'Trabajo / Estudio.' },
  { it: 'Nel tempo libero…', es: 'En el tiempo libre…' },
  { it: 'Mi piace leggere.', es: 'Me gusta leer.' },
  { it: 'Facciamo una passeggiata.', es: 'Demos un paseo.' },
  { it: 'Che tempo fa?', es: '¿Qué tiempo hace?' },
  { it: 'Piove.', es: 'Llueve.' },
  { it: 'C’è il sole.', es: 'Hay sol.' },
  { it: 'Fa freddo oggi.', es: 'Hace frío hoy.' },
  { it: 'Domani partiamo.', es: 'Mañana partimos.' },
  { it: 'Hai un minuto?', es: '¿Tienes un minuto?' },
  { it: 'Certo!', es: '¡Claro!' },
  { it: 'Naturalmente.', es: 'Naturalmente.' },
  { it: 'Forse.', es: 'Quizá.' },
  { it: 'Dipende.', es: 'Depende.' },
  { it: 'In bocca al lupo!', es: '¡Mucha suerte! (lit. en la boca del lobo)' },
  { it: 'Crepi!', es: '¡Gracias! (respuesta a In bocca al lupo)' },
  { it: 'Auguri!', es: '¡Felicidades!' },
  { it: 'Buon compleanno!', es: '¡Feliz cumpleaños!' },
  { it: 'Felice anno nuovo!', es: '¡Feliz año nuevo!' },
  { it: 'Buon Natale!', es: '¡Feliz Navidad!' },
  { it: 'Benvenuto / Benvenuta!', es: '¡Bienvenido / Bienvenida!' },
  { it: 'A casa mia.', es: 'En mi casa.' },
  { it: 'A casa tua.', es: 'En tu casa.' },
  { it: 'Di chi è?', es: '¿De quién es?' },
  { it: 'È mio / mia.', es: 'Es mío / mía.' },
  { it: 'Quanto tempo ci vuole?', es: '¿Cuánto tiempo se tarda?' },
  { it: 'Vicino / Lontano.', es: 'Cerca / Lejos.' },
  { it: 'Prima / Dopo.', es: 'Antes / Después.' },
  { it: 'Adesso o più tardi?', es: '¿Ahora o más tarde?' },
  { it: 'Non ancora.', es: 'Todavía no.' },
  { it: 'Già fatto.', es: 'Ya hecho.' },
  { it: 'Ci penso io.', es: 'Yo me encargo.' },
  { it: 'Fammi sapere.', es: 'Hazme saber.' },
  { it: 'Ti aspetto.', es: 'Te espero.' },
  { it: 'Ci sentiamo.', es: 'Hablamos / nos escuchamos.' },
  { it: 'Tutto bene?', es: '¿Todo bien?' },
  { it: 'Tutto a posto.', es: 'Todo en orden.' },
  { it: 'Che succede?', es: '¿Qué pasa?' },
  { it: 'Niente di speciale.', es: 'Nada especial.' },
  { it: 'Sono stanco / stanca.', es: 'Estoy cansado / cansada.' },
  { it: 'Sono impegnato / impegnata.', es: 'Estoy ocupado / ocupada.' },
  { it: 'Hai piani per stasera?', es: '¿Tienes planes para esta noche?' },
  { it: 'Andiamo a cena.', es: 'Vamos a cenar.' },
  { it: 'Ti va un caffè?', es: '¿Te apetece un café?' },
  { it: 'Perché no?', es: '¿Por qué no?' },
  { it: 'Assolutamente sì.', es: 'Absolutamente sí.' },
  { it: 'Neanch’io.', es: 'Yo tampoco.' },
  { it: 'Anch’io.', es: 'Yo también.' },
  { it: 'Come mai?', es: '¿Cómo es eso / por qué?' },
  { it: 'Non importa.', es: 'No importa.' },
  { it: 'Meglio di niente.', es: 'Mejor que nada.' },
  { it: 'Piano piano.', es: 'Despacio / poco a poco.' },
  { it: 'Forza!', es: '¡Ánimo!' },
  { it: 'Dai!', es: '¡Venga! / ¡Anda!' },
  { it: 'Figurati!', es: '¡Imagínate! / ¡No hay de qué!' },
  { it: 'Magari!', es: '¡Ojalá!' },
  { it: 'Boh.', es: 'Ni idea.' },
  { it: 'Ecco qui.', es: 'Aquí está.' },
  { it: 'Eccomi.', es: 'Aquí estoy.' },
  { it: 'Pronto?', es: '¿Diga? (al teléfono)' },
  { it: 'Chi parla?', es: '¿Quién habla?' },
  { it: 'Richiamo più tardi.', es: 'Devuelvo la llamada más tarde.' },
  { it: 'La linea è cattiva.', es: 'La línea está mala.' },
  { it: 'Mi sente?', es: '¿Me oye / escucha?' },
  { it: 'Grazie mille!', es: '¡Muchas gracias!' },
  { it: 'Tante grazie.', es: 'Muchas gracias.' },
  { it: 'Di niente.', es: 'De nada.' },
  { it: 'Prego, accomodati.', es: 'Por favor, ponte cómodo/a.' },
  { it: 'Dopo di te.', es: 'Después de ti.' },
  { it: 'Prima di tutto…', es: 'Antes que nada…' },
  { it: 'Alla fine…', es: 'Al final…' },
  { it: 'In altre parole…', es: 'En otras palabras…' },
  { it: 'Secondo me…', es: 'Según yo / en mi opinión…' },
  { it: 'A mio parere…', es: 'A mi parecer…' },
  { it: 'Sono d’accordo.', es: 'Estoy de acuerdo.' },
  { it: 'Non sono d’accordo.', es: 'No estoy de acuerdo.' },
  { it: 'Ha senso.', es: 'Tiene sentido.' },
  { it: 'Non ha senso.', es: 'No tiene sentido.' },
  { it: 'Ci pensiamo.', es: 'Lo pensamos.' },
  { it: 'Vediamo.', es: 'Veamos.' },
  { it: 'Proviamo.', es: 'Probemos.' },
  { it: 'Continuiamo.', es: 'Continuemos.' },
  { it: 'Facciamo una pausa.', es: 'Hagamos una pausa.' },
  { it: 'Di nuovo.', es: 'Otra vez / de nuevo.' },
  { it: 'Ancora una volta.', es: 'Una vez más.' },
  { it: 'Bastal!', es: '¡Basta!' },
  { it: 'Non esagerare.', es: 'No exageres.' },
  { it: 'Calma.', es: 'Calma.' },
  { it: 'Tranquillo / Tranquilla.', es: 'Tranquilo / Tranquila.' },
  { it: 'Non ti preoccupare.', es: 'No te preocupes.' },
  { it: 'Va tutto bene.', es: 'Todo va bien.' },
  { it: 'Sarà così.', es: 'Será así.' },
  { it: 'Chissà.', es: 'Quién sabe.' },
  { it: 'Speriamo.', es: 'Esperemos.' },
  { it: 'Incrociamo le dita.', es: 'Crucemos los dedos.' },
  { it: 'Tocchiamo ferro.', es: 'Toquemos madera.' },
  { it: 'In teoria…', es: 'En teoría…' },
  { it: 'In pratica…', es: 'En la práctica…' },
  { it: 'Per esempio…', es: 'Por ejemplo…' },
  { it: 'Cioè…', es: 'O sea…' },
  { it: 'Comunque…', es: 'De todos modos…' },
  { it: 'Allora…', es: 'Entonces…' },
  { it: 'Quindi…', es: 'Así que…' },
  { it: 'Insomma…', es: 'En resumen / en fin…' },
  { it: 'Alla prossima!', es: '¡Hasta la próxima!' },
  { it: 'Buona giornata!', es: '¡Que tengas un buen día!' },
  { it: 'Buona serata!', es: '¡Que tengas una buena noche!' },
  { it: 'Sogni d’oro!', es: '¡Dulces sueños!' },
  { it: 'Riposati.', es: 'Descansa.' },
  { it: 'Mi manchi.', es: 'Te echo de menos.' },
  { it: 'Ti voglio bene.', es: 'Te quiero (cariño / afecto).' },
  { it: 'Ti amo.', es: 'Te amo.' },
  { it: 'Congratulazioni!', es: '¡Felicitaciones!' },
  { it: 'Sei fantastico / fantastica!', es: '¡Eres fantástico / fantástica!' },
  { it: 'Bravo / Brava!', es: '¡Bravo / Bien hecho!' },
  { it: 'Ottimo lavoro!', es: '¡Excelente trabajo!' },
  { it: 'Non mollare!', es: '¡No te rindas!' },
  { it: 'Puoi farcela.', es: 'Puedes lograrlo.' },
  { it: 'Impariamo insieme.', es: 'Aprendamos juntos.' },
  { it: 'Studiamo italiano.', es: 'Estudiemos italiano.' },
  { it: 'Una parola al giorno.', es: 'Una palabra al día.' },
  { it: 'Cento parole per volta.', es: 'Cien palabras cada vez.' },
  { it: 'Piano, senza fretta.', es: 'Despacio, sin prisa.' },
  { it: 'Oggi imparo di più.', es: 'Hoy aprendo más.' },
  { it: 'Ripasso le parole.', es: 'Repaso las palabras.' },
  { it: 'Ho imparato qualcosa di nuovo.', es: 'Aprendí algo nuevo.' },
  { it: 'Mi ricordo questa parola.', es: 'Recuerdo esta palabra.' },
  { it: 'Quasi quasi…', es: 'Por poco / casi casi…' },
  { it: 'Proprio così.', es: 'Exactamente así.' },
  { it: 'Nemmeno per sogno.', es: 'Ni en sueños.' },
  { it: 'Meno male!', es: '¡Menos mal!' },
  { it: 'Purtroppo no.', es: 'Desafortunadamente no.' },
  { it: 'Per fortuna sì.', es: 'Por suerte sí.' },
  { it: 'Era ora!', es: '¡Ya era hora!' },
  { it: 'Finalmente!', es: '¡Por fin!' },
  { it: 'Che coincidenza!', es: '¡Qué coincidencia!' },
  { it: 'Che sorpresa!', es: '¡Qué sorpresa!' },
  { it: 'Non ci credo!', es: '¡No lo creo!' },
  { it: 'Davvero?', es: '¿De verdad?' },
  { it: 'Sul serio?', es: '¿En serio?' },
  { it: 'Scherzi?', es: '¿Bromeas?' },
  { it: 'Non scherzo.', es: 'No bromeo.' },
  { it: 'È uno scherzo.', es: 'Es una broma.' },
  { it: 'Parliamone.', es: 'Hablemos de ello.' },
  { it: 'Raccontami.', es: 'Cuéntame.' },
  { it: 'Dimmi tutto.', es: 'Dime todo.' },
  { it: 'Ascoltami.', es: 'Escúchame.' },
  { it: 'Guardami.', es: 'Mírame.' },
  { it: 'Seguimi.', es: 'Sígueme.' },
  { it: 'Aspettami qui.', es: 'Espérame aquí.' },
  { it: 'Torno subito.', es: 'Vuelvo enseguida.' },
  { it: 'Arrivo!', es: '¡Ya llego!' },
  { it: 'Sono arrivato / arrivata.', es: 'He llegado.' },
  { it: 'Siamo in ritardo.', es: 'Llegamos tarde.' },
  { it: 'Siamo in anticipo.', es: 'Llegamos temprano / con antelación.' },
  { it: 'C’è traffico.', es: 'Hay tráfico.' },
  { it: 'Prendiamo un taxi.', es: 'Tomemos un taxi.' },
  { it: 'Dov’è la stazione?', es: '¿Dónde está la estación?' },
  { it: 'Un biglietto di andata e ritorno.', es: 'Un billete de ida y vuelta.' },
  { it: 'Binario numero…', es: 'Andén número…' },
  { it: 'A che ora parte?', es: '¿A qué hora sale?' },
  { it: 'A che ora arriva?', es: '¿A qué hora llega?' },
  { it: 'Ho perso il treno.', es: 'Perdí el tren.' },
  { it: 'C’è un posto libero?', es: '¿Hay un asiento libre?' },
  { it: 'È occupato.', es: 'Está ocupado.' },
  { it: 'Posso sedermi qui?', es: '¿Puedo sentarme aquí?' },
  { it: 'Grazie per l’aiuto.', es: 'Gracias por la ayuda.' },
  { it: 'Hai bisogno di aiuto?', es: '¿Necesitas ayuda?' },
  { it: 'Sto cercando…', es: 'Estoy buscando…' },
  { it: 'Ho trovato!', es: '¡Encontré!' },
  { it: 'Ho perso…', es: 'He perdido…' },
  { it: 'Puoi aiutarmi?', es: '¿Puedes ayudarme?' },
  { it: 'Certo che sì.', es: 'Claro que sí.' },
  { it: 'Mi dispiace, non posso.', es: 'Lo siento, no puedo.' },
  { it: 'Un’altra volta.', es: 'En otra ocasión.' },
  { it: 'Quando vuoi.', es: 'Cuando quieras.' },
  { it: 'Quando puoi.', es: 'Cuando puedas.' },
  { it: 'Il prima possibile.', es: 'Lo antes posible.' },
  { it: 'Senza fretta.', es: 'Sin prisa.' },
  { it: 'Con calma.', es: 'Con calma.' },
  { it: 'Passo dopo passo.', es: 'Paso a paso.' },
  { it: 'Giorno per giorno.', es: 'Día a día.' },
  { it: 'Prima o poi.', es: 'Tarde o temprano.' },
  { it: 'Meglio tardi che mai.', es: 'Más vale tarde que nunca.' },
  { it: 'Tutto a suo tempo.', es: 'Todo a su tiempo.' },
  { it: 'Ogni inizio è difficile.', es: 'Todo comienzo es difícil.' },
  { it: 'La pratica rende perfetti.', es: 'La práctica hace al maestro.' },
  { it: 'Sbagliando s’impara.', es: 'Errando se aprende.' },
  { it: 'Non molliamo!', es: '¡No nos rindamos!' },
]

const phrases = []
let id = 1
for (let pack = 0; pack < 50; pack++) {
  for (let i = 0; i < 5; i++) {
    const base = BASE[(pack * 5 + i) % BASE.length]
    phrases.push({
      id: `p${String(id).padStart(4, '0')}`,
      pack,
      it: base.it,
      es: base.es,
    })
    id++
  }
}

mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(outPath, JSON.stringify(phrases, null, 0))
console.log(`Wrote ${phrases.length} phrases → ${outPath}`)
